# Read the Docs configuration file for PutPlace
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build documentation with Python 3.11
# The "latest" version will automatically track the default branch (main)
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # Install uv for faster dependency installation
      - pip install uv

# Install Python dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

# Output formats
formats:
  - pdf
  - epub
